"""empty message

Revision ID: 0050d0c6f61a
Revises: 438887b559e2
Create Date: 2021-04-09 02:22:47.220068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0050d0c6f61a'
down_revision = '438887b559e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'person', ['name'], unique=True)
    # ### end Alembic commands ###
