"""empty message

Revision ID: 0e06139a0951
Revises: 54ae45dc1519
Create Date: 2021-04-09 14:44:49.708090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e06139a0951'
down_revision = '54ae45dc1519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_of_birth', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
