"""empty message

Revision ID: 54ae45dc1519
Revises: 81fe341c5854
Create Date: 2021-04-09 03:04:52.072025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ae45dc1519'
down_revision = '81fe341c5854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'date_of_birth')
    # ### end Alembic commands ###
