"""empty message

Revision ID: 76d482d7b804
Revises: 27f4f5e3d277
Create Date: 2021-04-10 03:46:42.921195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76d482d7b804'
down_revision = '27f4f5e3d277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PeopleRelationship', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('PeopleRelationship', 'relatives')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PeopleRelationship', sa.Column('relatives', mysql.VARCHAR(length=200), nullable=True))
    op.alter_column('PeopleRelationship', 'person_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
