"""empty message

Revision ID: 81fe341c5854
Revises: 0050d0c6f61a
Create Date: 2021-04-09 02:50:03.023633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81fe341c5854'
down_revision = '0050d0c6f61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'father_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('person', 'mother_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'mother_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('person', 'father_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
